# Generated by Django 4.0 on 2023-01-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='Course',
            new_name='course',
        ),
    ]
