# Generated by Django 4.0 on 2023-01-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_acctivities_grade_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='activities',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='mid_term',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
