# Generated by Django 4.0 on 2023-01-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_grade_activities_alter_grade_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.CharField(default='000', max_length=10),
        ),
    ]
