# Generated by Django 4.0 on 2023-01-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_course_grade_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='acctivities',
            new_name='activities',
        ),
    ]
