# Generated by Django 4.0 on 2023-01-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_grade_activities_alter_grade_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='final',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='mid_term',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grades',
            field=models.ManyToManyField(blank=True, to='main.Grade'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
